Django/accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup,name="signup"), # 원가입
    # login
    path("login/", views.login,name="login"),
    # logout
    path("logout/", views.logout, name="logout"),
]

Django/articles/urls.py
from django.urls import path
from . import views

app_name="articles"
urlpatterns = [
    path("", views.index, name="index"),  # Todo: 게시글 전체 조회  ( / )
    # 게시글 상세 조회  ( /<int:id>/ )
    path("create/", views.create, name="create"), # 게시글 작성  ( /create/ )
    # 게시글 수정  ( /<int:id>/update/ )
    # 게시글 삭제  ( /<int:id>/delete/ )
]

Django/bakeries/urls.py
from django.urls import path
from . import views

app_name="bakeries"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:id>/delete/", views.delete, name="delete"),
    path("<int:id>/update/", views.update, name="update"),

    # ----- 테스트용
    path("test/", views.test, name="test"),
]

Django/bread_sisters/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bakeries/', include("bakeries.urls")),
    path('articles/', include("articles.urls")),
    path('accounts/', include("accounts.urls"))
]

Django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=100)

Django/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=20)  # 제목 (20글자 이내)
    content = models.TextField()  # 내용
    created_time = models.DateTimeField(auto_now_add=True)  # 생성일자 (자동생성)
    updated_time = models.DateTimeField(auto_now=True)  # 수정일자 (자동생성)

Django/bakeries/models.py
from django.db import models


class Bakery(models.Model):
    # 빵집 이름 (20자 이내)
    name = models.CharField(max_length=20)

    # 주소
    address = models.TextField()

    # 평점 (예: 0.0 ~ 5.0 범위 예상, 소수점 1자리까지)
    rating = models.FloatField()

    # 시작/종료 시간
    opening_time = models.DateTimeField()
    closing_time = models.DateTimeField()

    def __str__(self):
        return f'{self.name} ({self.rating}/10)'
    
    

Django/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User
class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        # fields = '__all__'
        fields = ('username',
                  'password1',
                  'password2',
                  'nickname',)

Django/articles/forms.py
from django import forms
from .models import Article


# Form vs ModelForm
# Form: 입력받을 데이터를 지정할 것이다
# ModelForm: DB 에 저장할 테이블만 입력 받을 것인가 ?

# class ArticleForm(forms.Form):
#     pass


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article

        labels = {
            'title' : '제목',
            'content' : "내용"
        }
        fields = "__all__"  # 전체 데이터를 입력받겠다
        # fields = ('title', )  # 특정 컬럼만 입력받겠다 (튜플, 리스트로 작성)

Django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import SignupForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            #자동 로그인
            auth_login(request,user)
            return redirect("bakeries:index")
    else:
        form = SignupForm()

    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect("bakeries:index")
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            nextUrl = request.GET.get('next')
            user = form.get_user()
            auth_login(request, user)
            if nextUrl:
                return redirect(nextUrl)
            return redirect("bakeries:index")
    else:
        form = AuthenticationForm()

    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('bakeries:index')

Django/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required


# 게시판 메인 페이지 (GET)
def index(request):
    # DB의 모든 articles 를 context 로 전달
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }
    response = render(request, "articles/index.html", context)
    response.set_cookie(
        key = "username",
        value = "yuyeon"
    )

    return render(request, "articles/index.html", context)


# 생성 페이지 (GET)
# 게시물 생성 (POST)
@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()

    context = {
        'form': form,
    }
    
    return render(request, "articles/create.html", context)

Django/bakeries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Bakery
from django.contrib.auth.decorators import login_required


def index(request):
    # DB의 Bakery 테이블에서 데이터를 모두 가져온다
    bakeries = Bakery.objects.all().order_by("-rating")
    # print(bakeries)
    # for bakery in bakeries:
    #     print(bakery)
        # print(bakery.name)
        # print(bakery.address)
        # print(bakery.rating)

    context = {
        "bakeries": bakeries,
    }
    
    return render(request, "bakeries/index.html", context)


from django.http import HttpResponseNotFound

def detail(request, id):
    # 데이터 하나를 조회
    # - get() 의 단점: 없는 데이터는 버그가 나버린다
    # bakery = Bakery.objects.get(pk=id)

    # - 개발 시에는 없으면, 에러 페이지로 이동해야 한다
    # bakery = Bakery.objects.filter(pk=id).first()
    # if bakery is None:
    #     return HttpResponseNotFound("<h1>잘못된 id 를 넣었다.</h1>")

    # - 실제 개발 시 많이 활용한다.
    bakery = get_object_or_404(Bakery, id=id)

    context = {
        'bakery': bakery,
    }

    return render(request, "bakeries/detail.html", context)


# 1. 생성하기 페이지 보여주기 (GET)
# 2. DB에 새로운 정보 저장 (POST)
@login_required
def create(request):
    if request.method == "POST":
        # request 에서 데이터 받아와서 DB에 저장
        print(request.POST)
        name = request.POST.get("name")
        address = request.POST.get("address")
        rating = request.POST.get("rating")
        opening_time = request.POST.get("opening_time")
        closing_time = request.POST.get("closing_time")

        # Bakery 저장
        # save vs create
        Bakery.objects.create(
            name=name,
            address=address,
            rating=rating,
            opening_time=opening_time,
            closing_time=closing_time,
        )
        
        # 메인페이지로 다시 요청을 보내줘야 함
        return redirect("bakeries:index")
    else:
        return render(request, "bakeries/create.html")



# 삭제
def delete(request, id):
    bakery = get_object_or_404(Bakery, id=id)
    bakery.delete()  # DB 에 삭제 요청
    print("삭제 완료!!!", bakery)  # 데이터가 있을까 없을까
    # 메인 페이지로 이동
    return redirect("bakeries:index")


# 수정
# 1. 수정 페이지 출력 (GET)
# 2. DB 에 데이터 수정 (POST)
def update(request, id):
    bakery = get_object_or_404(Bakery, id=id)

    if request.method == "POST":
        name = request.POST.get("name")
        address = request.POST.get("address")
        rating = request.POST.get("rating")
        opening_time = request.POST.get("opening_time")
        closing_time = request.POST.get("closing_time")

        bakery.name = name
        bakery.address = address
        bakery.rating = rating
        bakery.opening_time = opening_time
        bakery.closing_time = closing_time
        bakery.save()

        return redirect("bakeries:detail", bakery.id)
    else:
        context = {
            'bakery': bakery,
        }
        return render(request, "bakeries/update.html", context)


from django.utils import timezone
import random

def test(request):
    Bakery.objects.create(
        name="테스트 데이터",
        address="테스트 데이터",
        # 0 ~ 5 소수점 1자리
        rating=round(random.uniform(0.0, 5.0), 1),
        opening_time=timezone.now(),
        closing_time=timezone.now(),
    )
        
    # 메인페이지로 다시 요청을 보내줘야 함
    return redirect("bakeries:index")

Django/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <h1>로그인 페이지</h1>    
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>로그인하기</button>
    </form>
{% endblock content %}
    

Django/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>회원가입페이지</h1>    
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>회원 가입하기</button>
    </form>
{% endblock content %}
    

Django/articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
  <h1>게시글 생성하기</h1>
  
  <form action="" method = "POST">  
    {% csrf_token %}  
    {{ form.as_p }}
    <button>제출하기</button>
  </form>

{% endblock content %}


{% block content2 %}
  <h1>게시글 생성하기2</h1>
  
  <form action="" method = "POST">
    {% csrf_token %}  
    {{ form.as_p }}
    <button>제출하기</button>
  </form>

{% endblock content2 %}

Django/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
  <h1>게시판</h1>

  <a href="{% url "articles:create" %}"><button>생성하기</button></a>

  {% for article in articles %}
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <hr>
  {% empty %}
    <p>아직 등록된 게시글이 없습니다</p>
  {% endfor %}

{% endblock content %}

Django/bakeries/templates/bakeries/create.html
{% extends "base.html" %}

{% block content %}
  <h2>생성 페이지</h2>

  <form action="{% url 'bakeries:create' %}" method="POST">
    {% csrf_token %}
    <p>
      <label for="name">이름: </label>
      <input type="text" id="name" name="name" required>
    </p>

    <p>
      <label for="address">주소: </label>
      <input type="text" id="address" name="address" required>
    </p>

    <p>
      <label for="rating">평점: </label>
      <input type="number" 
        step="0.1" 
        id="rating" 
        name="rating" 
        min="0"
        max="10"
        required>
    </p>

    <p>
      <label for="opening_time">오픈 시간: </label>
      <input type="datetime-local" id="opening_time" name="opening_time" required>
    </p>

    <p>
      <label for="closing_time">마감 시간: </label>
      <input type="datetime-local" id="closing_time" name="closing_time" required>
    </p>

    <button>생성하기</button>
  </form>



{% endblock content %}

Django/bakeries/templates/bakeries/detail.html
{% extends "base.html" %}

{% block content %}
  <h2>상세 페이지</h2>

  <p>이름 : {{ bakery.name }}</p>
  <p>주소 : {{ bakery.address }}</p>
  <p>평점 : {{ bakery.rating }}</p>
  <p>오픈 시간 : {{ bakery.opening_time|date:"h:i A" }}</p>
  <p>마감 시간 : {{ bakery.closing_time|date:"h:i A" }}</p>
  
  <hr>

  <form action="{% url 'bakeries:delete' bakery.id %}" method="POST">
    {% csrf_token %}
    <button>삭제</button>
  </form>

  <a href="{% url "bakeries:update" bakery.id %}"><button>수정</button></a>
{% endblock content %}

Django/bakeries/templates/bakeries/index.html
{% extends "base.html" %}

{% block content %}
  <h2>메인 페이지</h2>

  <a href="{% url "bakeries:test" %}"><button>더미 데이터 생성</button></a> | 
  <a href="{% url 'bakeries:create' %}"><button>생성하기</button></a>

  {% for bakery in bakeries %}
    <p>이름 : <a href="{% url 'bakeries:detail' bakery.id %}">{{ bakery.name }}</a></p>
    <p>평점 : {{ bakery.rating }}</p>
    
    <hr>
  {% endfor %}

{% endblock content %}

Django/bakeries/templates/bakeries/update.html
{% extends "base.html" %}

{% block content %}
  <h2>수정 페이지</h2>

  <form action="{% url 'bakeries:update' bakery.id %}" method="POST">
    {% csrf_token %}
    <p>
      <label for="name">이름: </label>
      <input type="text" id="name" name="name" value="{{ bakery.name }}" required>
    </p>

    <p>
      <label for="address">주소: </label>
      <input type="text" id="address" name="address" value="{{ bakery.address }}" required>
    </p>

    <p>
      <label for="rating">평점: </label>
      <input type="number" 
        step="0.1" 
        id="rating" 
        name="rating" 
        min="0"
        max="10"
        value="{{ bakery.rating }}"
        required>
    </p>

    <p>
      <label for="opening_time">오픈 시간: </label>
      <input type="datetime-local" id="opening_time" name="opening_time" value="{{ bakery.opening_time|date:'Y-m-d\\TH:i' }}" required>
    </p>

    <p>
      <label for="closing_time">마감 시간: </label>
      <input type="datetime-local" id="closing_time" name="closing_time" value="{{ bakery.closing_time|date:'Y-m-d\\TH:i' }}" required>
    </p>

    <button>수정하기</button>
  </form>



{% endblock content %}